export const EMPLOYMENT_CATEGORIES = [
    "Software Engineer",
    "Doctor",
    "Teacher",
    "Civil Engineer",
    "Mechanical Engineer",
    "Accountant",
    "Chartered Accountant",
    "Bank Manager",
    "Clerk",
    "Govt Employee",
    "Nurse",
    "Police Officer",
    "Army/Defense",
    "Business Owner",
    "Lawyer",
    "Professor",
    "Scientist",
    "Artist",
    "Architect",
    "Designer",
    "Marketing Professional",
    "HR Professional",
    "Sales Professional",
    "Journalist",
    "Social Worker",
    "Farmer",
    "Driver",
    "Electrician",
    "Plumber",
    "Chef",
    "Merchant Navy",
    "Aviation",
    "Civil Services",
    "Student",
    "Retired",
    "Other"
] as const;
