export const EMPLOYMENT_CATEGORIES = [
    "Software Engineer",
    "Doctor",
    "Teacher",
    "Civil Engineer",
    "Mechanical Engineer",
    "Accountant",
    "Chartered Accountant",
    "Bank Manager",
    "Clerk",
    "Govt Employee",
    "Nurse",
    "Police Officer",
    "Army/Defense",
    "Business Owner",
    "Lawyer",
    "Professor",
    "Scientist",
    "Artist",
    "Architect",
    "Designer",
    "Marketing Professional",
    "HR Professional",
    "Sales Professional",
    "Journalist",
    "Social Worker",
    "Farmer",
    "Driver",
    "Electrician",
    "Plumber",
    "Chef",
    "Merchant Navy",
    "Aviation",
    "Civil Services",
    "Student",
    "Retired",
    "Other"
] as const;

export const COUNTRY_CODES = [
    { code: "+91", country: "India" },
    { code: "+93", country: "Afghanistan" },
    { code: "+355", country: "Albania" },
    { code: "+213", country: "Algeria" },
    { code: "+376", country: "Andorra" },
    { code: "+244", country: "Angola" },
    { code: "+54", country: "Argentina" },
    { code: "+374", country: "Armenia" },
    { code: "+61", country: "Australia" },
    { code: "+43", country: "Austria" },
    { code: "+994", country: "Azerbaijan" },
    { code: "+973", country: "Bahrain" },
    { code: "+880", country: "Bangladesh" },
    { code: "+375", country: "Belarus" },
    { code: "+32", country: "Belgium" },
    { code: "+975", country: "Bhutan" },
    { code: "+55", country: "Brazil" },
    { code: "+855", country: "Cambodia" },
    { code: "+1", country: "Canada" },
    { code: "+86", country: "China" },
    { code: "+57", country: "Colombia" },
    { code: "+20", country: "Egypt" },
    { code: "+358", country: "Finland" },
    { code: "+33", country: "France" },
    { code: "+49", country: "Germany" },
    { code: "+30", country: "Greece" },
    { code: "+852", country: "Hong Kong" },
    { code: "+36", country: "Hungary" },
    { code: "+354", country: "Iceland" },
    { code: "+62", country: "Indonesia" },
    { code: "+98", country: "Iran" },
    { code: "+964", country: "Iraq" },
    { code: "+353", country: "Ireland" },
    { code: "+39", country: "Italy" },
    { code: "+81", country: "Japan" },
    { code: "+962", country: "Jordan" },
    { code: "+254", country: "Kenya" },
    { code: "+965", country: "Kuwait" },
    { code: "+60", country: "Malaysia" },
    { code: "+960", country: "Maldives" },
    { code: "+52", country: "Mexico" },
    { code: "+977", country: "Nepal" },
    { code: "+31", country: "Netherlands" },
    { code: "+64", country: "New Zealand" },
    { code: "+234", country: "Nigeria" },
    { code: "+47", country: "Norway" },
    { code: "+968", country: "Oman" },
    { code: "+92", country: "Pakistan" },
    { code: "+63", country: "Philippines" },
    { code: "+48", country: "Poland" },
    { code: "+351", country: "Portugal" },
    { code: "+974", country: "Qatar" },
    { code: "+7", country: "Russia" },
    { code: "+966", country: "Saudi Arabia" },
    { code: "+65", country: "Singapore" },
    { code: "+27", country: "South Africa" },
    { code: "+82", country: "South Korea" },
    { code: "+34", country: "Spain" },
    { code: "+94", country: "Sri Lanka" },
    { code: "+46", country: "Sweden" },
    { code: "+41", country: "Switzerland" },
    { code: "+66", country: "Thailand" },
    { code: "+90", country: "Turkey" },
    { code: "+971", country: "UAE" },
    { code: "+44", country: "UK" },
    { code: "+1", country: "USA" },
    { code: "+84", country: "Vietnam" },
] as const;
